baseurl = "http://jackyu.io/"
languageCode = "en-us"
title = "JackYu | CodeDogFish"
theme = "purehugo"
Paginate = 10
disqusShortname = "CodeDogFish"

[params]
  twitterName = "CodeDogFish"
  githubName = "CodeDogFish"
  description = "Hello world!"
  
